//created on: 2018-12-08
package netflix

//list any import classes here.
import netflix.Netflix.Question
import netflix.Netflix.NetflixWindow

import java.util.List
import java.util.Arrays
import java.util.ArrayList

import javax.swing.JFrame
import javax.swing.JTextPane
import javax.swing.JRadioButton


//declare any global variables here
//global JFrame frame
global JTextPane textPane

//problem z arraylist, drools nie chce przemielic - pojedyncze buttony?
//global List buttons 



rule 'Init'
	when
	then
		System.out.println("init");
		//buttons = new ArrayList <JRadioButton>;
		addQuestion(textPane, 
		 	//buttons, 
			new Question("What SF series should I watch on Netflix?", 
			Arrays.asList("SciFi", "Horror", "Slipstream", "Fantasy")));
end

rule 'Scifi'
	when 
		q : Question(description.equals("What SF series should I watch on Netflix?") 
			&& selected.equals("SciFi"))
		
	then
		System.out.println("scifi");
		addQuestion(textPane, 
			//buttons, 
			new Question("Like anthologies?", 
			Arrays.asList("Yep", "Nope")));
		
end


function void addQuestion(JTextPane textPane, /*List <JRadioButton> buttons,*/ Question question) {
	
	textPane.setText(question.description);
	
	/*
	for (JRadioButton jRadioButton : buttons) {
		jRadioButton.setVisible(false);	
	}
	
	int i = 0;
	for (String choice : question.choices) {
			buttons.get(i).setText(choice);
			buttons.get(i).setVisible(true);
			i++;				
		}
	*/
}






